version: '3.5'

networks:
  frontend:
    name: frontend
  storage:
    name: storage

services:
  traefik:
    image: traefik:v1.7
    command: --api --docker
    ports:
      # only expose https to outside world
      - "443:443"   # SSL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$PWD/traefik/config/traefik.toml:/etc/traefik/traefik.toml"
      - "$PWD/traefik/certs/:/certs/"
    labels:
      - "traefik.enable=true"
    depends_on:
      - apim_gateway
      - apim_console
      - apim_portal
      - apim_management
      - am_gateway
      - am_management
      - am_console
    networks:
      frontend:
        aliases:
          - am.gravitee.io

  mongodb:
    image: mongo:${MONGODB_VERSION:-3.4}
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=gravitee
    labels:
      - "traefik.enable=false"
    volumes:
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/mongo:/data/db
    networks:
      - storage

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.3.1}
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
    ulimits:
      nofile: 65536
    labels:
      - "traefik.enable=false"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - storage

  apim_gateway:
    image: graviteeio/apim-gateway:${APIM_VERSION:-3}
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
    volumes:
      - "$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts"
    labels:
      - "traefik.frontend.rule=Host:apim.gravitee.io"
      - "traefik.backend=graviteeio-apim-gateway"
      - "traefik.port=8082"
      - "traefik.docker.network=frontend"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - storage
      - frontend

  apim_console:
    image: graviteeio/apim-management-ui:${APIM_VERSION:-3}
    restart: always
    environment:
      - MGMT_API_URL=https:\/\/apim.gravitee.io\/api\/management\/organizations\/DEFAULT\/environments\/DEFAULT\/
    volumes:
      - "$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts"
    labels:
      - "traefik.frontend.redirect.regex=^https://apim.gravitee.io/console$$"
      - "traefik.frontend.redirect.replacement=https://apim.gravitee.io/console/"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.port=8080"
      # Warn: do not use PathPrefixStrip cause it not works well with redirect (https://github.com/containous/traefik/issues/1957#issuecomment-359369625)
      - "traefik.frontend.rule=Host:apim.gravitee.io;PathPrefix:/console;ReplacePathRegex: ^/console/(.*) /$$1"
      - "traefik.docker.network=frontend"
    depends_on:
      - apim_management
    networks:
      - frontend

  apim_portal:
    image: graviteeio/apim-portal-ui:${APIM_VERSION:-3}
    restart: always
    environment:
      - PORTAL_BASE_HREF=/portal/
      - PORTAL_API_URL=https:\/\/apim.gravitee.io\/api\/portal\/environments\/DEFAULT
    volumes:
      - "$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts"
    labels:
      - "traefik.frontend.redirect.regex=^https://apim.gravitee.io/portal$$"
      - "traefik.frontend.redirect.replacement=https://apim.gravitee.io/portal/"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:apim.gravitee.io;PathPrefix:/portal;ReplacePathRegex: ^/portal/(.*) /$$1"
      - "traefik.docker.network=frontend"
    depends_on:
      - apim_management
    networks:
      - frontend

  apim_management:
    image: graviteeio/apim-management-api:${APIM_VERSION:-3}
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
      - gravitee_jwt_cookiepath=/api
      - gravitee_jwt_cookiesecure=true
      - gravitee_jwt_cookiedomain=apim.gravitee.io
    volumes:
      - "$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts"
    labels:
      - "traefik.frontend.rule=Host:apim.gravitee.io;PathPrefixStrip:/api"
      - "traefik.backend=graviteeio-apim-management-api"
      - "traefik.port=8083"
      - "traefik.docker.network=frontend"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - storage
      - frontend

  am_gateway:
    image: graviteeio/am-gateway:${AM_VERSION:-3}
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    volumes:
      - "$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts"
    labels:
      - "traefik.backend=graviteeio-am-gateway"
      - "traefik.frontend.rule=Host:am.gravitee.io;PathPrefixStrip:/auth"
      - "traefik.port=8092"
      - "traefik.docker.network=frontend"
    depends_on:
      - mongodb
    networks:
      - storage
      - frontend

  am_management:
    image: graviteeio/am-management-api:${AM_VERSION:-3}
    restart: always
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_jwt_cookiepath=/
      - gravitee_jwt_cookiesecure=true
      - gravitee_jwt_cookiedomain=am.gravitee.io
    volumes:
      - "$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts"
    labels:
      - "traefik.backend=graviteeio-am-managementapi"
      - "traefik.frontend.rule=Host:am.gravitee.io;PathPrefix:/management,/admin"
      - "traefik.port=8093"
      - "traefik.docker.network=frontend"
    depends_on:
      - mongodb
    networks:
      - storage
      - frontend

  am_console:
    image: graviteeio/am-management-ui:${AM_VERSION:-3}
    restart: always
    environment:
      - MGMT_API_URL=https:\/\/am.gravitee.io${AM_MGT_API_BASE:-}
      - MGMT_UI_URL=https:\/\/am.gravitee.io
    labels:
      - "traefik.backend=graviteeio-am-managementui"
      - "traefik.frontend.rule=Host:am.gravitee.io"
      - "traefik.docker.network=frontend"
      - "traefik.port=8080"
    depends_on:
      - am_management
    networks:
      - frontend
